let name = prompt ("vad heter du?")
 console.log (`name: ${name}`)
 let age = prompt ("hur gammal är du?")
 console.log (`age: ${age}`)
 let adress = prompt ("vad är din adress??")
 console.log (`adress: ${adress}`)
 let postnummer = prompt ("vad är ditt postnummer?")
 console.log (`\t \t ${postnummer}`)
 let telefonnummer = prompt ("vad är ditt telfonnummer?")
 console.log (`telefon: ${telefonnummer}`)
